version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "11:00"
  commit-message:
    prefix: ⬆️
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: webpack
    versions:
    - ^5.0.0
